kind: pipeline
name: Testing

steps:
  - name: Testing
    image: golang
    volumes:
      - name: gosrc
        path: /go/src
    commands:
      - go get github.com/go-sql-driver/mysql
      - go get github.com/mingchoi/struct2sql
      - go get github.com/tucnak/telebot
      - go test -v
      - go vet

  - name: Build
    image: golang
    volumes:
      - name: gosrc
        path: /go/src
      - name: release
        path: /drone/release
    commands:
      - go build -v -a -o /drone/release/linux/amd64/lock9

  - name: Show path
    image: golang
    volumes:
      - name: gosrc
        path: /go/src
      - name: release
        path: /drone/release
    commands:
      - pwd
      - ls
      - ls /drone/release/linux/amd64/
      - ls /go/src/github.com

volumes:
  - name: gosrc
    temp: {}
  - name: release
    temp: {}
