kind: pipeline
name: Testing

steps:
  - name: Testing
    image: golang
    volumes:
      - name: gosrc
        path: /go/src
    commands:
      - go get github.com/go-sql-driver/mysql
      - go get github.com/mingchoi/struct2sql
      - go get github.com/tucnak/telebot
      - go test -v
      - go vet

  - name: Build
    image: golang
    volumes:
      - name: gosrc
        path: /go/src
      - name: release
        path: /drone/release
    commands:
      - go build -v -a -o /drone/release/linux/amd64/lock9

  - name: Publish
    image: plugins/docker
    volumes:
      - name: release
        path: /drone/src/release
    settings:
      repo: mingchoi/lock9
      auto_tag: true
      dockerfile: Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - push
        - tag

volumes:
  - name: gosrc
    temp: {}
  - name: release
    temp: {}
